In [20]:
import pandas as pd
import numpy as np

In [21]:
house_data = pd.read_csv("housepricedata.csv")

In [22]:
house_data

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [23]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
LotArea             1460 non-null int64
OverallQual         1460 non-null int64
OverallCond         1460 non-null int64
TotalBsmtSF         1460 non-null int64
FullBath            1460 non-null int64
HalfBath            1460 non-null int64
BedroomAbvGr        1460 non-null int64
TotRmsAbvGrd        1460 non-null int64
Fireplaces          1460 non-null int64
GarageArea          1460 non-null int64
AboveMedianPrice    1460 non-null int64
dtypes: int64(11)
memory usage: 125.6 KB


In [24]:
house_data.isnull().sum()

LotArea             0
OverallQual         0
OverallCond         0
TotalBsmtSF         0
FullBath            0
HalfBath            0
BedroomAbvGr        0
TotRmsAbvGrd        0
Fireplaces          0
GarageArea          0
AboveMedianPrice    0
dtype: int64

In [25]:
house_data.head(10)

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0     8450            7            5          856         2         1   
1     9600            6            8         1262         2         0   
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   
5    14115            5            5          796         1         1   
6    10084            8            5         1686         2         0   
7    10382            7            6         1107         2         1   
8     6120            7            5          952         2         0   
9     7420            5            6          991         1         0   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0             3             8           0         548                 1  
1             3             6           1         460                 1  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1  
5             1             5           0         480                 0  
6             3             7           1         636                 1  
7             3             7           2         484                 1  
8             2             8           2         468                 0  
9             2             5           2         205                 0

In [26]:
house_data.tail(10)

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
1450     9000            5            5          896         2         2   
1451     9262            8            5         1573         2         0   
1452     3675            5            5          547         1         0   
1453    17217            5            5         1140         1         0   
1454     7500            7            5         1221         2         0   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
1450             4             8           0           0                 0  
1451             3             7           1         840                 1  
1452             2             5           0         525                 0  
1453             3             6           0           0                 0  
1454             2             6           0         400                 1  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0

In [27]:
house_data.shape

(1460, 11)

array([1, 1, 1, ..., 1, 0, 0])

## Data splitting

In [43]:
x = house_data.iloc[:,0:10]
x

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  
0                3             8           0         548  
1                3             6           1         460  
2                3             6           1         608  
3                3             7           1         642  
4                4             9           1         836  
...            ...           ...         ...         ...  
1455             3             7           1         460  
1456             3             7           2         500  
1457             4             9           2         252  
1458             2             5           0         240  
1459             3             6           0         276  

[1460 rows x 10 columns]

In [44]:
y = np.ravel(house_data.AboveMedianPrice)

In [57]:
from sklearn.model_selection import train_test_split

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [72]:
from sklearn.preprocessing import MinMaxScaler

In [73]:
scaler = MinMaxScaler()
scaler.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [74]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [75]:
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout

In [76]:
model = Sequential()

In [77]:
model.add(Dense(32, activation="relu", input_shape=(10,)))
model.add(Dense(32, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [78]:
model.compile(optimizer="sgd", loss="binary_crossentropy", metrics = ["accuracy"])

In [79]:
model.fit(x_train, y_train, epochs=100, batch_size=32)

Train on 1168 samples
Epoch 1/100
1168/1168 [==============================] - 0s 297us/sample - loss: 0.6879 - accuracy: 0.5120
Epoch 2/100
1168/1168 [==============================] - 0s 36us/sample - loss: 0.6820 - accuracy: 0.5120
Epoch 3/100
1168/1168 [==============================] - 0s 36us/sample - loss: 0.6772 - accuracy: 0.5120
Epoch 4/100
1168/1168 [==============================] - 0s 35us/sample - loss: 0.6730 - accuracy: 0.5146
Epoch 5/100
1168/1168 [==============================] - 0s 36us/sample - loss: 0.6691 - accuracy: 0.5180
Epoch 6/100
1168/1168 [==============================] - 0s 35us/sample - loss: 0.6655 - accuracy: 0.5283
Epoch 7/100
1168/1168 [==============================] - 0s 33us/sample - loss: 0.6617 - accuracy: 0.5548
Epoch 8/100
1168/1168 [==============================] - 0s 37us/sample - loss: 0.6576 - accuracy: 0.5728
Epoch 9/100
1168/1168 [==============================] - 0s 34us/sample - loss: 0.6533 - accuracy: 0.6079
Epoch 10/100
1168/1168 

In [80]:
results = model.evaluate(x_test, y_test)

292/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [81]:
predictions = model.predict(x_test)

In [94]:
predictions[:10]

array([[0.02439997],
       [0.9935124 ],
       [0.08744943],
       [0.78677064],
       [0.99001783],
       [0.01421046],
       [0.78240305],
       [0.8468511 ],
       [0.01422033],
       [0.04670015]], dtype=float32)

In [93]:
y_test[:10]

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0])